package org.example.interfaces;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author vicen
 */
public class Login extends javax.swing.JFrame {

    static final String url = "jdbc:mysql://localhost:3306/users";
    static final String user = "root";
    static final String passwd = "";

    static Connection c;
    static Statement s;
    static ResultSet r;

    /**
     * Creates new form Log1n
     */
    public Login() {
        initComponents();
        configInicial();
    }

    public void configInicial() {
        setLocationRelativeTo(null);
        setTitle("NSLM GoalTracker");
        setIconImage(new ImageIcon(getClass().getResource("images/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        panelEncabezado = new javax.swing.JPanel();
        lblIcono1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblIcono2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtFieldUser = new LIB.JTexfieldPH_FielTex();
        lblCrearCuenta = new javax.swing.JLabel();
        txtFieldPasswd = new LIB.JTexfieldPH_Password();
        btnLogin = new javax.swing.JButton();
        lblRayo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEncabezado.setBackground(new java.awt.Color(0, 51, 0));

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelLogin.add(panelEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 50));

        lblIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/interfaces/images/iconoUser.png"))); // NOI18N
        panelLogin.add(lblIcono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, 60));
        panelLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 230, 20));

        lblIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/interfaces/images/iconPasswd.png"))); // NOI18N
        panelLogin.add(lblIcono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 30, 40));
        panelLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, 10));

        txtFieldUser.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldUser.setBorder(null);
        txtFieldUser.setPlaceholder("Usuario");
        panelLogin.add(txtFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 30));

        lblCrearCuenta.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 10)); // NOI18N
        lblCrearCuenta.setForeground(new java.awt.Color(0, 0, 0));
        lblCrearCuenta.setText("¿No tienes cuenta?");
        lblCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearCuentaMouseClicked(evt);
            }
        });
        panelLogin.add(lblCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, 40));

        txtFieldPasswd.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldPasswd.setBorder(null);
        txtFieldPasswd.setPlaceholder("Contraseña");
        panelLogin.add(txtFieldPasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        btnLogin.setBackground(new java.awt.Color(153, 255, 153));
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 290, 40));

        panelFondo.add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 350, 330));

        lblRayo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/interfaces/images/rayo.png"))); // NOI18N
        lblRayo.setText("jLabel1");
        panelFondo.add(lblRayo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 440, 400));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/interfaces/images/fondo.jpg"))); // NOI18N
        panelFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearCuentaMouseClicked
        new CrearCuenta().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblCrearCuentaMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            c = DriverManager.getConnection(url, user, passwd);
            s = c.createStatement();

            r = s.executeQuery("SELECT * FROM usuario WHERE nombre = '" + txtFieldUser.getText() + "'");
            r.next();

            try {
                r.getString("password").equals(txtFieldPasswd.getText());
                this.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Verifique su usuario/contraseña.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado");
        }

        IndexClasificacion ic = new IndexClasificacion();
        ic.setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCrearCuenta;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIcono1;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblRayo;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelLogin;
    private LIB.JTexfieldPH_Password txtFieldPasswd;
    private LIB.JTexfieldPH_FielTex txtFieldUser;
    // End of variables declaration//GEN-END:variables
}
