package org.example.interfaces;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author vicen
 */
public class Login extends javax.swing.JFrame{

    /**
     * Creates new form Lgin
     */
    public Login() {
        initComponents();
        this.configInicial();
        
    }
    
    public void configInicial(){
        setLocationRelativeTo(null);
        setTitle("NSLM GoalTracker");
        setIconImage(new ImageIcon(getClass().getResource("images/icono.png")).getImage());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNTC = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtFieldPasswd = new javax.swing.JPasswordField();
        txtFieldUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblniciarSesion = new javax.swing.JLabel();
        fotoRayo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CREAR CUENTA");
        panelBackground.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        lblNTC.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        lblNTC.setForeground(new java.awt.Color(0, 0, 0));
        lblNTC.setText("�No tienes cuenta?");
        panelBackground.add(lblNTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        lblLogin.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(0, 0, 0));
        lblLogin.setText("LOGIN");
        panelBackground.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 60, 40));

        txtFieldPasswd.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldPasswd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBackground.add(txtFieldPasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 270, 20));

        txtFieldUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBackground.add(txtFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 270, 20));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Contrase�a");
        panelBackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Usuario");
        panelBackground.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        lblniciarSesion.setBackground(new java.awt.Color(204, 204, 204));
        lblniciarSesion.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        lblniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        lblniciarSesion.setText("Iniciar Sesion");
        panelBackground.add(lblniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        fotoRayo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/interfaces/images/rayo.png"))); // NOI18N
        panelBackground.add(fotoRayo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 550, 410));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/interfaces/images/fondo.jpg"))); // NOI18N
        fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelBackground.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fotoRayo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNTC;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblniciarSesion;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPasswordField txtFieldPasswd;
    private javax.swing.JTextField txtFieldUsuario;
    // End of variables declaration                   
}
